/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mendel;

/**Programador: Juan Galíndez
 * cl:27.665.373
 * correo:juanegalindezberlioz@gmail.com
 */
public class Vista extends javax.swing.JFrame {

    /**
     * Creates new form Vista
     */
    public Vista() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton_Salir = new javax.swing.JButton();
        jButton_ley1 = new javax.swing.JButton();
        jButton_ley2 = new javax.swing.JButton();
        jButton_ley3 = new javax.swing.JButton();
        jButton_Ayuda = new javax.swing.JButton();
        jLabel_Titulo = new javax.swing.JLabel();
        jLabelFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton_Salir.setBackground(new java.awt.Color(204, 0, 0));
        jButton_Salir.setText("Salir");
        jButton_Salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_SalirActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_Salir, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 273, 60, 20));

        jButton_ley1.setBackground(new java.awt.Color(102, 255, 255));
        jButton_ley1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton_ley1.setText("Uniformidad");
        getContentPane().add(jButton_ley1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, -1, 20));

        jButton_ley2.setBackground(new java.awt.Color(102, 255, 255));
        jButton_ley2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton_ley2.setText("Segregación");
        getContentPane().add(jButton_ley2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 133, 110, 20));

        jButton_ley3.setBackground(new java.awt.Color(102, 255, 255));
        jButton_ley3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton_ley3.setText("Transmision indepediente");
        getContentPane().add(jButton_ley3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 193, -1, 20));

        jButton_Ayuda.setBackground(new java.awt.Color(102, 255, 255));
        jButton_Ayuda.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton_Ayuda.setText("Ayuda");
        getContentPane().add(jButton_Ayuda, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 273, -1, 20));

        jLabel_Titulo.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel_Titulo.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_Titulo.setText("Bienvenido a APG!");
        getContentPane().add(jLabel_Titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 170, -1));

        jLabelFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fondo-adn_23-2148162710.jpg"))); // NOI18N
        getContentPane().add(jLabelFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_SalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_SalirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton_SalirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Vista().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton jButton_Ayuda;
    public javax.swing.JButton jButton_Salir;
    public javax.swing.JButton jButton_ley1;
    public javax.swing.JButton jButton_ley2;
    public javax.swing.JButton jButton_ley3;
    private javax.swing.JLabel jLabelFondo;
    private javax.swing.JLabel jLabel_Titulo;
    // End of variables declaration//GEN-END:variables
}
